services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/dbname
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
      - web
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A mycelery flower
    ports:
      - "5555:5555"
    depends_on:
      - celery
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_data:
  

