services:
  web:
    build: .
    ports:
      - ./env
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=./env
      - REDIS_URL=./env
    volumes:
      - .:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    depends_on:
      - redis
      - web
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ./env

  redis:
    image: redis:latest
    ports:
      - ./env
    volumes:
      - redis_data:/data

  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A mycelery flower
    ports:
      - ./env
    depends_on:
      - celery
    environment:
      - REDIS_URL=./env

volumes:
  postgres_data:
  redis_data:
  

