"""empty message

Revision ID: 0795476e3a5a
Revises: d37013ed6658
Create Date: 2024-11-22 21:45:39.773704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0795476e3a5a'
down_revision: Union[str, None] = 'd37013ed6658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'transaction',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('category_id', sa.Integer, sa.ForeignKey('category.id'), nullable=False),
        sa.Column('title', sa.String, nullable=False),
        sa.Column('amount', sa.Float, nullable=False),
        sa.Column('date', sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transaction', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    # ### end Alembic commands ###
