"""empty message

Revision ID: bba344e9def5
Revises: 0795476e3a5a
Create Date: 2024-11-23 09:08:09.660036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bba344e9def5'
down_revision: Union[str, None] = '0795476e3a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'wallet', ['wallet_id'], ['id'])
    op.drop_column('user', 'wallet_ids')
    op.add_column('wallet', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'])
    op.drop_column('wallet', 'transaction_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('transaction_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'user_id')
    op.add_column('user', sa.Column('wallet_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'wallet_id')
    # ### end Alembic commands ###
