"""empty message

Revision ID: edcca1056d01
Revises: bba344e9def5
Create Date: 2024-11-23 23:01:57.109589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcca1056d01'
down_revision: Union[str, None] = 'bba344e9def5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('is_shared', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'is_shared')
    # ### end Alembic commands ###
